### ISSUE TITLE
How to migrate so that our Spring Boot 3 works with the multitude of Spring Boot 2.x in our network

### ISSUE THREAD

**Issue by jmart1** [micrometer-metrics/tracing#272]
We upgraded one of our apps to Spring Boot 3.  Now the tracing is no longer working.  We looked at the migration guide, but the guide doesn't really give steps for how to get our upgraded app to work as it was before.  Remember, apps get upgraded one at a time in a network that typically contains many more Spring Boot apps.  So it has to work with all the existing apps that are not in Spring Boot 3.  

How can I get our newly upgraded Spring Boot 3 app to do the same exact thing it did before so that it works as expected with the many Spring Boot 2.x apps?  I'm referring to the tracing ID (with span and parent IDs) being generated or passed along on all inbound REAST API requests and all outbound RestTemplate API calls.

**Comment by jmart1** [comment]
https://stackoverflow.com/a/76373792/1490322

**Comment by kioyong** [comment]
Hi @jmart1 ,i have similar issue when upgrade to SpringBoot 3.1.x, please find below my config change when upgrade to 3.x
hope can help you~ 

SpringBoot 2.7.x config:
```yaml
spring:
  sleuth:
    baggage:
      correlation-enabled: true
      correlation-fields: testId
      remote-fields: testId
    propagation:
      type: CUSTOM #B3,W3C e.tc
```
dependency:
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-sleuth</artifactId>
</dependency>
```

Spring Boot 3.1.x config:
```yaml
management:
  tracing:
    enabled: true
    baggage:
      correlation:
        enabled: true
        fields: testId
      remote-fields: testId
    propagation:
      type: B3

```
dependency:
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>
```
